### ISSUE TITLE
G-sync missing after using the tool

### ISSUE THREAD

**Issue by frankxu2004** [RealistikDash/genshin-fps-bypass#4]
First of all, thanks for the great tool, I have used the other fps unlocker before and I am so glad that there's a pure python version now. However this version seems to suffer from a similar problem as in https://github.com/34736384/genshin-fps-unlock/issues/327 . They seem to have fixed the issue and I wonder if you have any thoughts on why this might be the case? Thanks!

**Comment by frankxu2004** [comment]
Seems like the only difference between 3.0.2 and 3.0.3 is https://github.com/34736384/genshin-fps-unlock/commit/d6b6a2523be03438f2c853173a4e296817a967b2

**Comment by RealistikDash** [comment]
Hey,

Interesting issue, I'll try to investigate soon. Usually have GSync off so this issue did slip through my tests. 

Quick question, is this issue replicable on FreeSync monitors with GSync enabled through the Nvidia panel?

Thanks!

**Comment by frankxu2004** [comment]
Yes, I have a FreeSync monitor as well and enabled Gsync via nvidia panel, plus enabling that little indicator on the right-up corner.
![image](https://github.com/RealistikDash/genshin-fps-bypass/assets/6738274/c783c94d-c72c-4baf-ae5a-78b6ee21a51d)

**Comment by RealistikDash** [comment]
Okay apologies for the delay. I am not sure if I am interpreting this issue correctly (I am interpreting it as being unable to set the FPS below the refresh rate if using G-Sync) but I don't think I am able to replicate this issue.

I am running an 175hz display.
![image](https://github.com/RealistikDash/genshin-fps-bypass/assets/36131887/5838ca34-fba2-469c-bc34-163539c07834)
![image](https://github.com/RealistikDash/genshin-fps-bypass/assets/36131887/98e3d50b-17d5-4289-8636-4f0c6c2d1b2d)
![image](https://github.com/RealistikDash/genshin-fps-bypass/assets/36131887/f3b072fc-3fa0-4689-bef2-8e8b6c8734cf)
